-- Auto-generated by cbor2lean4 from shards/binding-ontology/clifford_rs.cbor
namespace CliffordBindings

inductive CborVal where
  | cnat    : Nat → CborVal
  | cneg    : Nat → CborVal
  | cbytes  : List Nat → CborVal
  | ctext   : String → CborVal
  | carray  : List CborVal → CborVal
  | cmap    : List (CborVal × CborVal) → CborVal
  | ctag    : Nat → CborVal → CborVal
  | cbool   : Bool → CborVal
  | cnull   : CborVal
  | cfloat  : Nat → CborVal
deriving Repr, BEq

open CborVal

def da51Tag : Nat := 55889

def shard_0 : CborVal :=
  (ctag 55889 (cmap [
      ((ctext "decl_blade"), (ctext "0x7b5b")),
      ((ctext "decl_count"), (cnat 126)),
      ((ctext "decl_grade"), (cnat 11)),
      ((ctext "decls"), (carray [
          (cmap [
            ((ctext "blade"), (ctext "0x0100")),
            ((ctext "blade_bit"), (cnat 8)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "use")),
            ((ctext "prime"), (cnat 23)),
            ((ctext "subject"), (ctext "serde::{..}"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0002")),
            ((ctext "blade_bit"), (cnat 1)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "const")),
            ((ctext "prime"), (cnat 3)),
            ((ctext "subject"), (ctext "LEECH_KISSING_NUMBER"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0002")),
            ((ctext "blade_bit"), (cnat 1)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "const")),
            ((ctext "prime"), (cnat 3)),
            ((ctext "subject"), (ctext "DIM"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0002")),
            ((ctext "blade_bit"), (cnat 1)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "const")),
            ((ctext "prime"), (cnat 3)),
            ((ctext "subject"), (ctext "BLADE_COUNT"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0008")),
            ((ctext "blade_bit"), (cnat 3)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "struct")),
            ((ctext "prime"), (cnat 7)),
            ((ctext "subject"), (ctext "Multivector"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "blades"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0040")),
            ((ctext "blade_bit"), (cnat 6)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "impl")),
            ((ctext "prime"), (cnat 17)),
            ((ctext "subject"), (ctext "Multivector"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "new"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "scalar"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "vector"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "geometric_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "grade"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "scalar_part"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "zero"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "norm"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "extract_component"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "blade"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "mv"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "mv"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "out"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "index"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "sign"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "value"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "result"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "blade_sign"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "count"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "b_shifted"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0010")),
            ((ctext "blade_bit"), (cnat 4)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "enum")),
            ((ctext "prime"), (cnat 11)),
            ((ctext "subject"), (ctext "Watchtower"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "East"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "West"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "South"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "North"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0008")),
            ((ctext "blade_bit"), (cnat 3)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "struct")),
            ((ctext "prime"), (cnat 7)),
            ((ctext "subject"), (ctext "ResonanceBasin"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "id"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "watchtower"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "attractor"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "prime_factor"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0008")),
            ((ctext "blade_bit"), (cnat 3)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "struct")),
            ((ctext "prime"), (cnat 7)),
            ((ctext "subject"), (ctext "MonsterManifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "basins"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "current_state"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0040")),
            ((ctext "blade_bit"), (cnat 6)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "impl")),
            ((ctext "prime"), (cnat 17)),
            ((ctext "subject"), (ctext "MonsterManifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "new"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "walk_to_basin"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "cosine_interpolate"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "inner_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "wedge_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "export_ganja_js"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "primes"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "basins"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "interpolated"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "mu"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "result"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0200")),
            ((ctext "blade_bit"), (cnat 9)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "mod")),
            ((ctext "prime"), (cnat 29)),
            ((ctext "subject"), (ctext "tests"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0100")),
            ((ctext "blade_bit"), (cnat 8)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "use")),
            ((ctext "prime"), (cnat 23)),
            ((ctext "subject"), (ctext "super::*"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_manifold_creation"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "manifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_basin_walk"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "manifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_geometric_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "a"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "b"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "c"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_blade_sign"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "s1"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "s2"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0100")),
            ((ctext "blade_bit"), (cnat 8)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "use")),
            ((ctext "prime"), (cnat 23)),
            ((ctext "subject"), (ctext "serde::{..}"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0002")),
            ((ctext "blade_bit"), (cnat 1)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "const")),
            ((ctext "prime"), (cnat 3)),
            ((ctext "subject"), (ctext "LEECH_KISSING_NUMBER"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0002")),
            ((ctext "blade_bit"), (cnat 1)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "const")),
            ((ctext "prime"), (cnat 3)),
            ((ctext "subject"), (ctext "DIM"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0002")),
            ((ctext "blade_bit"), (cnat 1)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "const")),
            ((ctext "prime"), (cnat 3)),
            ((ctext "subject"), (ctext "BLADE_COUNT"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0008")),
            ((ctext "blade_bit"), (cnat 3)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "struct")),
            ((ctext "prime"), (cnat 7)),
            ((ctext "subject"), (ctext "Multivector"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "blades"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0040")),
            ((ctext "blade_bit"), (cnat 6)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "impl")),
            ((ctext "prime"), (cnat 17)),
            ((ctext "subject"), (ctext "Multivector"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "new"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "scalar"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "vector"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "geometric_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "grade"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "scalar_part"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "mv"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "mv"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "out"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "index"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "sign"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "value"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "result"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "blade_sign"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "count"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "b_shifted"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0010")),
            ((ctext "blade_bit"), (cnat 4)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "enum")),
            ((ctext "prime"), (cnat 11)),
            ((ctext "subject"), (ctext "Watchtower"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "East"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "West"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "South"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x2000")),
            ((ctext "blade_bit"), (cnat 13)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "variant")),
            ((ctext "prime"), (cnat 59)),
            ((ctext "subject"), (ctext "North"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0008")),
            ((ctext "blade_bit"), (cnat 3)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "struct")),
            ((ctext "prime"), (cnat 7)),
            ((ctext "subject"), (ctext "ResonanceBasin"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "id"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "watchtower"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "attractor"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "prime_factor"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0008")),
            ((ctext "blade_bit"), (cnat 3)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "struct")),
            ((ctext "prime"), (cnat 7)),
            ((ctext "subject"), (ctext "MonsterManifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "basins"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x1000")),
            ((ctext "blade_bit"), (cnat 12)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "field")),
            ((ctext "prime"), (cnat 47)),
            ((ctext "subject"), (ctext "current_state"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0040")),
            ((ctext "blade_bit"), (cnat 6)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "impl")),
            ((ctext "prime"), (cnat 17)),
            ((ctext "subject"), (ctext "MonsterManifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "new"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "walk_to_basin"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "cosine_interpolate"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "inner_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "wedge_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x4000")),
            ((ctext "blade_bit"), (cnat 14)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "method")),
            ((ctext "prime"), (cnat 71)),
            ((ctext "subject"), (ctext "export_ganja_js"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "primes"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "basins"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "interpolated"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "mu"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "result"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0200")),
            ((ctext "blade_bit"), (cnat 9)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "mod")),
            ((ctext "prime"), (cnat 29)),
            ((ctext "subject"), (ctext "tests"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0100")),
            ((ctext "blade_bit"), (cnat 8)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "use")),
            ((ctext "prime"), (cnat 23)),
            ((ctext "subject"), (ctext "super::*"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_manifold_creation"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "manifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_basin_walk"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "manifold"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_geometric_product"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "a"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "b"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "c"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0001")),
            ((ctext "blade_bit"), (cnat 0)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "fn")),
            ((ctext "prime"), (cnat 2)),
            ((ctext "subject"), (ctext "test_blade_sign"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "s1"))
          ]),
          (cmap [
            ((ctext "blade"), (ctext "0x0800")),
            ((ctext "blade_bit"), (cnat 11)),
            ((ctext "object"), (ctext "clifford.rs")),
            ((ctext "predicate"), (ctext "let")),
            ((ctext "prime"), (cnat 41)),
            ((ctext "subject"), (ctext "s2"))
          ])
        ])),
      ((ctext "file"), (ctext "clifford.rs"))
    ]))

theorem shard_0_is_da51 : ∃ v, shard_0 = ctag da51Tag v := ⟨_, rfl⟩

def allShards : List CborVal :=
  [shard_0]

end CliffordBindings
