-- Auto-generated by cbor2lean4 from shards/binding-ontology/ontology_global.cbor
namespace BindingOntology

inductive CborVal where
  | cnat    : Nat → CborVal
  | cneg    : Nat → CborVal
  | cbytes  : List Nat → CborVal
  | ctext   : String → CborVal
  | carray  : List CborVal → CborVal
  | cmap    : List (CborVal × CborVal) → CborVal
  | ctag    : Nat → CborVal → CborVal
  | cbool   : Bool → CborVal
  | cnull   : CborVal
  | cfloat  : Nat → CborVal
deriving Repr, BEq

open CborVal

def da51Tag : Nat := 55889

def shard_0 : CborVal :=
  (ctag 55889 (cmap [
      ((ctext "composite_blade"), (ctext "0x7ffb")),
      ((ctext "composite_grade"), (cnat 14)),
      ((ctext "fractran_blade"), (ctext "0x05e2")),
      ((ctext "kind_counts"), (cmap [
          ((ctext "const"), (cnat 172)),
          ((ctext "enum"), (cnat 24)),
          ((ctext "field"), (cnat 1063)),
          ((ctext "fn"), (cnat 754)),
          ((ctext "impl"), (cnat 183)),
          ((ctext "let"), (cnat 4349)),
          ((ctext "macro"), (cnat 3)),
          ((ctext "method"), (cnat 834)),
          ((ctext "mod"), (cnat 158)),
          ((ctext "struct"), (cnat 283)),
          ((ctext "trait"), (cnat 1)),
          ((ctext "type"), (cnat 4)),
          ((ctext "use"), (cnat 654)),
          ((ctext "variant"), (cnat 153))
        ])),
      ((ctext "lineage"), (cmap [
          ((ctext "build_rs"), (ctext "build.rs (DeclVisitor + ZosVisitor + FractranExtractor)")),
          ((ctext "mkbootstrap"), (ctext "/mnt/data1/meta-introspector/src/mkbootstrap.rs")),
          ((ctext "mkbuildrs"), (ctext "/mnt/data1/nix/vendor/rust/cargo2nix/submodules/patch-build-rs/patch-build-rs-macros/src/mkbuildrs.rs"))
        ])),
      ((ctext "ontology"), (ctext "mmgroup-rust-bindings")),
      ((ctext "total_decls"), (cnat 8635)),
      ((ctext "total_files"), (cnat 197)),
      ((ctext "version"), (ctext "1.0")),
      ((ctext "zkperf_registers"), (cmap [
          ((ctext "r0"), (cmap [
              ((ctext "count"), (cnat 754)),
              ((ctext "kind"), (ctext "fn")),
              ((ctext "prime"), (cnat 2))
            ])),
          ((ctext "r1"), (cmap [
              ((ctext "count"), (cnat 172)),
              ((ctext "kind"), (ctext "const")),
              ((ctext "prime"), (cnat 3))
            ])),
          ((ctext "r10"), (cmap [
              ((ctext "count"), (cnat 3)),
              ((ctext "kind"), (ctext "macro")),
              ((ctext "prime"), (cnat 31))
            ])),
          ((ctext "r11"), (cmap [
              ((ctext "count"), (cnat 4349)),
              ((ctext "kind"), (ctext "let")),
              ((ctext "prime"), (cnat 41))
            ])),
          ((ctext "r12"), (cmap [
              ((ctext "count"), (cnat 1063)),
              ((ctext "kind"), (ctext "field")),
              ((ctext "prime"), (cnat 47))
            ])),
          ((ctext "r13"), (cmap [
              ((ctext "count"), (cnat 153)),
              ((ctext "kind"), (ctext "variant")),
              ((ctext "prime"), (cnat 59))
            ])),
          ((ctext "r14"), (cmap [
              ((ctext "count"), (cnat 834)),
              ((ctext "kind"), (ctext "method")),
              ((ctext "prime"), (cnat 71))
            ])),
          ((ctext "r2"), (cmap [
              ((ctext "count"), (cnat 0)),
              ((ctext "kind"), (ctext "static")),
              ((ctext "prime"), (cnat 5))
            ])),
          ((ctext "r3"), (cmap [
              ((ctext "count"), (cnat 283)),
              ((ctext "kind"), (ctext "struct")),
              ((ctext "prime"), (cnat 7))
            ])),
          ((ctext "r4"), (cmap [
              ((ctext "count"), (cnat 24)),
              ((ctext "kind"), (ctext "enum")),
              ((ctext "prime"), (cnat 11))
            ])),
          ((ctext "r5"), (cmap [
              ((ctext "count"), (cnat 4)),
              ((ctext "kind"), (ctext "type")),
              ((ctext "prime"), (cnat 13))
            ])),
          ((ctext "r6"), (cmap [
              ((ctext "count"), (cnat 183)),
              ((ctext "kind"), (ctext "impl")),
              ((ctext "prime"), (cnat 17))
            ])),
          ((ctext "r7"), (cmap [
              ((ctext "count"), (cnat 1)),
              ((ctext "kind"), (ctext "trait")),
              ((ctext "prime"), (cnat 19))
            ])),
          ((ctext "r8"), (cmap [
              ((ctext "count"), (cnat 654)),
              ((ctext "kind"), (ctext "use")),
              ((ctext "prime"), (cnat 23))
            ])),
          ((ctext "r9"), (cmap [
              ((ctext "count"), (cnat 158)),
              ((ctext "kind"), (ctext "mod")),
              ((ctext "prime"), (cnat 29))
            ]))
        ])),
      ((ctext "zos_blade"), (ctext "0x5704"))
    ]))

theorem shard_0_is_da51 : ∃ v, shard_0 = ctag da51Tag v := ⟨_, rfl⟩

def allShards : List CborVal :=
  [shard_0]

end BindingOntology
